#ifndef ENUMS_H
#define ENUMS_H

enum TOOL {PENCIL, ERASER, CIRCLE, TRIANGLE, RECTANGLE, POLYGON, SELECTOR};

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET};

enum ACTION {NONE, CLEAR, SEND_TO_BACK, SEND_TO_FRONT, INCREASE_SIZE, DECREASE_SIZE};

#endif